"""phase5_discovery_sessions_messages

Revision ID: 8263f043ec9b
Revises: d09c9a933355
Create Date: 2026-03-15 09:34:34.481691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8263f043ec9b'
down_revision: Union[str, None] = 'd09c9a933355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_sessions',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('detected_pain_points', sa.JSON(), nullable=True),
    sa.Column('matched_capabilities', sa.JSON(), nullable=True),
    sa.Column('recommended_package', sa.String(length=50), nullable=True),
    sa.Column('blueprint', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_sessions_workspace_id'), 'discovery_sessions', ['workspace_id'], unique=False)
    op.create_table('discovery_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['discovery_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_messages_session_id'), 'discovery_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_messages_session_id'), table_name='discovery_messages')
    op.drop_table('discovery_messages')
    op.drop_index(op.f('ix_discovery_sessions_workspace_id'), table_name='discovery_sessions')
    op.drop_table('discovery_sessions')
    # ### end Alembic commands ###
