"""portal_builder

Revision ID: d09c9a933355
Revises: a0e527de9a3a
Create Date: 2026-03-15 07:57:53.769889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09c9a933355'
down_revision: Union[str, None] = 'a0e527de9a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_sessions',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=320), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_sessions_quote_id'), 'portal_sessions', ['quote_id'], unique=False)
    op.create_index(op.f('ix_portal_sessions_token'), 'portal_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_portal_sessions_workspace_id'), 'portal_sessions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_sessions_workspace_id'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_token'), table_name='portal_sessions')
    op.drop_index(op.f('ix_portal_sessions_quote_id'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    # ### end Alembic commands ###
